name: CI/CD for dbt Project

on:
  push:
    branches:
      - master  # Trigger the workflow on push to 'master'
    paths:
      - 'iagc/models/**'               # Trigger when models in iagc folder change
      - 'iagc/dbt_project.yml'          # Trigger when the dbt project configuration changes
      - 'iagc/macros/**'                # Trigger when macros are modified in the iagc folder
  pull_request:
    branches:
      - master  # Run the workflow for PRs to the 'master' branch
    paths:
      - 'iagc/models/**'
      - 'iagc/dbt_project.yml'
      - 'iagc/macros/**'

jobs:
  dbt-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'  # Use Python 3.8 or any other compatible version

    # Navigate to the iagc directory where dbt_project.yml is located
    - name: Change to iagc directory
      run: cd iagc

    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-snowflake  # Adjust based on your dbt adapter (e.g., dbt-postgres)
    
    # Check if the dbt-target artifact exists
    - name: Check if dbt-target artifact exists
      id: check_artifact
      run: |
        echo "Checking if dbt-target artifact exists..."
        if curl -s --head --fail "${{ github.server_url }}/${{ github.repository }}/actions/artifacts/${{ github.run_id }}" | grep -q '200 OK'; then
          echo "::set-output name=found::true"
        else
          echo "::set-output name=found::false"
        fi
        
    - name: Download dbt target directory from previous run
      if: ${{ steps.check_artifact.outputs.found == 'true' }}
      uses: actions/download-artifact@v3
      with:
        name: dbt-target  # The artifact name used in previous runs
        path: target/     # The path to restore the target directory 

    - name: Run dbt models (only changed models)
      run: |
        dbt deps
        dbt seed
        dbt run --select state:modified+ --state target/
      working-directory: ./iagc

    - name: Run dbt tests (only changed models)
      run: dbt test --select state:modified+ --state target/
      working-directory: ./iagc

    - name: Upload dbt target directory
      uses: actions/upload-artifact@v3
      with:
        name: dbt-target
        path: iagc/target/