name: CI/CD for dbt Project

on:
  push:
    branches:
      - master
    paths:
      - 'iagc/models/**'
      - 'iagc/dbt_project.yml'
      - 'iagc/macros/**'
  pull_request:
    branches:
      - master
    paths:
      - 'iagc/models/**'
      - 'iagc/dbt_project.yml'
      - 'iagc/macros/**'

jobs:
  dbt-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Use Python 3.8 for compatibility

    - name: Install dbt
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-snowflake
      working-directory: ./iagc

    - name: Check if dbt-target artifact exists
      id: check_artifact
      run: |
        if curl -s --head --fail "${{ github.server_url }}/${{ github.repository }}/actions/artifacts/${{ github.run_id }}" | grep -q '200 OK'; then
          echo "Artifact found"
          echo "found=true" >> $GITHUB_ENV
        else
          echo "Artifact not found"
          echo "found=false" >> $GITHUB_ENV

    - name: Download dbt target directory from previous run
      if: env.found == 'true'
      uses: actions/download-artifact@v3
      with:
        name: dbt-target
        path: target/
      working-directory: ./iagc

    - name: Run dbt models (only changed models)
      run: |
        dbt deps
        dbt seed
        dbt run --select state:modified+ --state target/
      working-directory: ./iagc

    - name: Run dbt tests (only changed models)
      run: dbt test --select state:modified+ --state target/
      working-directory: ./iagc

    - name: Upload dbt target directory
      uses: actions/upload-artifact@v3
      with:
        name: dbt-target
        path: iagc/target/
