name: CI/CD Workflow Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Test Message
      run: echo "Running the CI/CD workflow"
