name: Test GitHub Actions

on:
  push:
    branches:
      - master  # Run the workflow on push to 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World!"
